### ISSUE TITLE
Need help setting it up

### ISSUE THREAD

**Issue by BubblePlayzTHEREAL** [lumpn/unity-discord#1]
Do you think you could make or link a video showing how to set this up?

**Comment by BubblePlayzTHEREAL** [comment]
its mainly the "Create a `WebhookData` asset" thing im confused on

**Comment by lumpn** [comment]
Check out the `Webhook Sample` that comes with the package. You can import the sample from the package manager.

![image](https://github.com/lumpn/unity-discord/assets/7193990/8f67483f-e1d0-4e3e-9070-6f083687f155)

To create a new `WebhookData` asset, use Assets &rarr; Create &rarr; Data &rarr; Discord &rarr; WebhookData in Unity's file menu.
