### ISSUE TITLE
[Feature] Support for files (sending images directly and more)

### ISSUE THREAD

**Issue by ndumais** [lumpn/unity-discord#2]
Hey, first of all, thanks for this repo, works well out of the box without needing any work

Would be nice to be able to use the file API to send the file and also add it as an attachment. Here's the best doc I found on it https://birdie0.github.io/discord-webhooks-guide/structure/file.html

But basically it needs to use **Content-Type: multipart/form-data** so it can't be done with only embeds currently, and I can't simply add a struct because it would also slightly affect how the payload is sent afaik.

The struct that would be handled a bit differently than others would need fields for **fileName**, **fileType** and **fileExtension** at least I think.

```csharp
namespace Lumpn.Discord
{
    [Serializable]
    public struct File
    {
        public string fileName;
        
        public string fileType; // example: "image/png"
        
        public string fileExtension; // exemple: ".png" or "png" depending on the implemention you prefer
    }
}
```

And then, for it to be attached it would also need to be in the embeded, which can most likely already be done with the current code base

**Comment by lumpn** [comment]
> Would be nice to be able to use the file API to send the file and also add it as an attachment. Here's the best doc I found on it https://birdie0.github.io/discord-webhooks-guide/structure/file.html

Oh, nice! I didn't know it was possible to attach files via webhooks.

**Comment by lumpn** [comment]
> The struct that would be handled a bit differently than others would need fields for **fileName**, **fileType** and **fileExtension** at least I think.

It was quite a bit more complicated than that, but it works now.

```csharp
IEnumerator Start()
{
    var img = ImageData.Create(MediaType.PNG, imageBytes);

    var webhook = webhookData.CreateWebhook();
    return webhook.Send(text, img);
}
```

**Comment by ndumais** [comment]
Nice implementation, easier to use than what I expected, only issue I see is that limits the feature to only working with images. For example you currently can't send a file with ".txt" extension for an error log which is also an important use-case because messages are limited to 2000 characters, while files can contain much more data.

You went for a much cleaner image implementation that really takes into account the image type instead of strings for type "image/png" and extension ".png" and I think this is easier to understand and use overall though!

**Comment by lumpn** [comment]
> you currently can't send a file with ".txt" extension for an error log which is also an important use-case because messages are limited to 2000 characters, while files can contain much more data.

Fixed. You can now attach text files and ".zip" archives.

**Comment by ndumais** [comment]
> > you currently can't send a file with ".txt" extension for an error log which is also an important use-case because messages are limited to 2000 characters, while files can contain much more data.
> 
> Fixed. You can now attach text files and ".zip" archives.

I think you should be able to send an embed with attachments too?
I'm doing a few tests right now but not sure if it'll work, I'll post the code here if it does

**Comment by ndumais** [comment]
For some reason does not seem I can change a signature or add a method temporarily in an external package, although I can modify what's inside one, I think something like that should work?

```csharp
  public static IEnumerator Send(this Webhook webhook, Embed embed, FileData[] files)
  {
      var message = new Message
      {
          username = webhook.name,
          embeds = new[] { embed },
          files = files,
      };
      return Send(webhook, message, files);
  }
```

Might import all of the code in my codebase later to experiment more with it!

**Comment by ndumais** [comment]
It does seem to work with the **code above** and possibly small tweaks, only weird thing is that the file is at the top instead of the bottom, but that's really a detail at this point!

![image](https://github.com/user-attachments/assets/412c057b-2280-4785-ac79-abe860918525)

![image](https://github.com/user-attachments/assets/ef30bbb9-23e2-49ca-9fa7-7937069cad5b)

**Comment by lumpn** [comment]
> I think you should be able to send an embed with attachments too?

I don't think so, no. This is not a limitation of webhooks but of Discord. I've never seen an embed with an attachment on Discord and the official Discord documentation does not mention anything like that either.

> It does seem to work with the **code above** and possibly small tweaks, only weird thing is that the file is at the top instead of the bottom, but that's really a detail at this point!

Yes, you can send a message and embeds at the same time. It's highly unusual and nobody ever does that, but the API allows it. It just ends up looking... not great in Discord.

In your case I wouldn't use embeds. Throw the stack trace in the message, attach the log and the screenshot, done.

```csharp
var screenshot = FileData.Create(MediaType.JPEG, screenshotBytes);
var log = FileData.Create(MediaType.Text, logFileBytes);
webhook.Send(stackTrace, new[] { screenshot, log });
```

**Comment by ndumais** [comment]
Yeah, probably unusual, although an example of file (image outside) + embeds is shown in the unofficial doc I sent you, not that it looks super good.. Haven't seen much info on how all of this works from the official documentation when I was searching.

Either ways, huge thanks for the fast replies and file updates, I hope more people find this!

**Comment by lumpn** [comment]
> Yeah, probably unusual, although an example of file (image outside) + embeds is shown in the unofficial doc I sent you

Sorry, I can't find it. Can you link me to the example you're referencing?

**Comment by lumpn** [comment]
Oh wait, I think I misunderstood you. You said:

> I think you should be able to send an embed with attachments too?

And I understood "an embed _containing_ attachments". I don't think embeds can _contain_ attachments, meaning there can be lots of things _inside_ the frame of an embed, like a title, a thumbnail, a footer, and an image, but not an attachment.

But you never said you wanted the attachment to show up inside the frame. You just want to send it together _with_ the embed in the same call, right?

If so, that's totally doable, and you're right, the code you posted does exactly that. 👍

```csharp
public static IEnumerator Send(this Webhook webhook, Embed embed, FileData[] files)
{
  var message = new Message
  {
    username = webhook.name,
    embeds = new[] { embed },
    files = files,
  };
  return Send(webhook, message, files);
}
```

> only weird thing is that the file is at the top instead of the bottom

Yes, if you send a message and embeds at the same time, then message text will display on top, followed by images and attachments, followed by the embeds at the bottom. I don't like it either, but that's just how Discord works.

**Comment by ndumais** [comment]
Ah yeah definitely a misunderstanding!

Did mean having an embed AND an attachment in the same payload, although the idea of having the attachment within the embed might be nice, I don't think it's supported or possible.

You can see an example of what I meant here (first example)
https://birdie0.github.io/discord-webhooks-guide/structure/file.html
